### ISSUE TITLE
No license present

### ISSUE THREAD

**Issue by XJDHDR** [bartekmuzyk/IniParser#1]
Good day

I am interested in using this code in one of my projects. However, I've noticed that there is no license either in the repo or mentioned in the docs. Unfortunately, this means that anyone who sees this repo is only allowed to look at the code and/or fork the repo. Nothing else is permitted.

Please can you add a license file to clarify what people can and can't do with this code? Thanks!

**Comment by bartekmuzyk** [comment]
Hey, thanks for reaching out, I have now added a LICENSE file to the master branch. Please note however, that this library doesn't fully meet the spec of INI files and may fail in unexpected ways. Also, this package isn't available in any NuGet repository, which makes it hard to maintain the newest version in your project easily. Consider choosing an actively maintained package, like [salaros/config-parser](https://github.com/salaros/config-parser).
